#!/bin/bash

a=" Vimrc"
b="Yazi.toml"
c="Waybar config"
d="Mako config"
e="Sway config"
f="Stuff2remember"
g="Configuration.nix"
h="Flake.nix"
i="Pkgs"
j="Add new script"
ai="\0icon\x1fvim"
bi="\0icon\x1fsystem-file-manager"
ci="\0icon\x1fwayland"
di="\0icon\x1fnotion"
ei="\0icon\x1fdesktop-effects"
fi="\0icon\x1fnotepad"
gi="\0icon\x1fpreferences-system-services"
hi="\0icon\x1fpreferences-system-services"
ii="\0icon\x1fpreferences-system-services"
ji="\0icon\x1fadd"

selected=$(echo -e "s\t$e$ei\nv\t$a$ai\ny\t$b$bi\nw\t$c$ci\nm\t$d$di\nr\t$f$fi\na\t$j$ji" | fuzzel --match-mode exact --with-nth 2 --accept-nth 2 --match-nth 1 --lines 17 --auto-select -d )
case $selected in
    "$a")
        $TERMINAL -e vim ~/.config/vim/vimrc;;
    "$b")
        $TERMINAL -e vim ~/.config/yazi/keymap.toml;;
    "$c")
        $TERMINAL -e vim ~/.config/waybar/config-sway.jsonc;;
    "$d")
        $TERMINAL -e vim ~/.config/mako/config;;
    "$e")
        $TERMINAL -e vim ~/.config/sway/config;;
    "$f")
        $TERMINAL -e vim ~/.dotfiles/other/stuff2remember.txt;;
    "$g")
        $TERMINAL -e vim ~/.dotfiles/nixos/hosts/zbook/configuration.nix;;
    "$h")
        $TERMINAL -e vim ~/.dotfiles/nixos/flake.nix;;
    "$i")
        $TERMINAL -e vim ~/.dotfiles/nixos/modules/pkgs.nix;;
    "$j")
        addnew
esac
