#!/bin/bash

a="Gmail"
b="nNixOS search"
c="pPřehraj.to"
d="sSdílej.cz"
e="tTitulky.cz"
f="Fonts"
ai="\0icon\x1fgmail"
bi="\0icon\x1fkmag"
ci="\0icon\x1fdeepin-media-player"
di="\0icon\x1fdeepin-media-player"
ei="\0icon\x1fapplication-rtf"
fi="\0icon\x1ffonts"

selected=$(echo -e "$a$ai\n$b$bi\n$c$ci\n$d$di\n$e$ei\n$f$fi" | fuzzel --auto-select -d )
case $selected in
    "$a")
        brave https://mail.google.com/mail/u/0/;;
    "$b")
        brave https://search.nixos.org/packages;;
    "$c")
        brave https://prehrajto.cz/;;
    "$d")
        brave https://sdilej.cz/;;
    "$e")
        brave http://titulky.com/;;
    "$f")
        brave https://www.nerdfonts.com/cheat-sheet;;
esac
